### ISSUE TITLE
Log in to the registry

### ISSUE THREAD

**Issue by bluetree7878** [modern-agile-team/8term-coko-Front#26]
## 📌 이슈 내용
CI/CD 깃허브 액션이 레지스트리 로그인에서 막혔습니다. 이를 수정하겠습니다.

### 구현 내용
- [ ] 깃허브 액션 버그 수정

### 🖥️관련 화면 (선택사항)
```
# 배포 Job
  deploy:
    needs: build  # build 후에 실행되도록 정의
    name: Deploy
    runs-on: [ self-hosted, label-go ] # AWS ./configure에서 사용할 label명
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
```
